"""Command-line interface: generate, compare, and inspect backends.

    clm backends
    clm generate --corpus data/tiny_shakespeare.txt --backend deflate \
        --prompt "MENENIUS:" --length 200 --temperature 0.8
    clm compare --corpus data/tiny_shakespeare.txt --prompt "KING:" \
        --length 120 --out reports/
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import __version__, backends
from .compare import SPEED_BUDGET, render_markdown, run_comparison, write_report
from .engine import GenerationConfig, generate
from .metrics import corpus_overlap, self_repetition


def _parse_opt(pairs: list[str]) -> dict[str, object]:
    """Parse repeatable --opt key=value into backend_options."""
    opts: dict[str, object] = {}
    for pair in pairs or []:
        key, sep, val = pair.partition("=")
        if not sep:
            raise SystemExit(f"--opt expects key=value, got {pair!r}")
        for cast in (int, float):
            try:
                val = cast(val)  # type: ignore[assignment]
                break
            except ValueError:
                continue
        opts[key] = val
    return opts


def _add_search_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("--beam-width", type=int, default=None)
    p.add_argument(
        "--lookahead", type=int, default=None, help="span depth planned and committed per round"
    )
    p.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help="0 = most compressible span; >0 samples final beams",
    )
    p.add_argument(
        "--context-bytes",
        type=int,
        default=None,
        help="corpus tail bytes primed (default: backend limit)",
    )
    p.add_argument("--memory", type=int, default=128, help="generated bytes visible to the scorer")
    p.add_argument("--tiebreak", choices=["corpus", "none"], default="corpus")
    p.add_argument(
        "--corpus-gate",
        action="store_true",
        help="only score candidates present in the context (strict recombination; much faster)",
    )
    p.add_argument("--repeat-penalty", type=float, default=0.0)
    p.add_argument("--workers", type=int, default=1)
    p.add_argument("--seed", type=int, default=None)
    p.add_argument(
        "--opt",
        action="append",
        default=[],
        metavar="KEY=VAL",
        help="backend option, repeatable (e.g. --opt level=9 --opt preset=3)",
    )


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="clm",
        description="Text generation and comparison with compressors as language models.",
    )
    p.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("backends", help="list registered compressor backends")

    g = sub.add_parser("generate", help="generate a continuation with one backend")
    g.add_argument("--corpus", type=Path, required=True)
    g.add_argument("--backend", default="deflate")
    g.add_argument("--prompt", default="")
    g.add_argument("--prompt-file", type=Path)
    g.add_argument("--length", type=int, default=200)
    g.add_argument("--stats", action="store_true", help="print metrics to stderr")
    _add_search_args(g)

    c = sub.add_parser("compare", help="run one prompt across backends")
    c.add_argument("--corpus", type=Path, required=True)
    c.add_argument("--backends", default="all", help="comma-separated names, or 'all' (default)")
    c.add_argument("--prompt", default="")
    c.add_argument("--prompt-file", type=Path)
    c.add_argument("--length", type=int, default=120)
    c.add_argument(
        "--out", type=Path, default=Path("reports"), help="report directory (default: reports/)"
    )
    c.add_argument("--no-write", action="store_true", help="print the report without writing files")
    _add_search_args(c)
    return p


def _read_prompt(args: argparse.Namespace) -> bytes:
    if getattr(args, "prompt_file", None):
        return args.prompt_file.read_bytes()
    return args.prompt.encode("utf-8", errors="replace")


def _cmd_backends() -> int:
    print(f"{'backend':<10} {'family':<16} {'package':<14} {'speed':<7} {'ctx':<6} status")
    for i in backends.all_info():
        status = "available" if i.available else f"missing: {i.unavailable_reason}"
        print(
            f"{i.name:<10} {i.family:<16} {i.package:<14} {i.speed:<7} "
            f"{i.context_limit:<6} {status}"
        )
    return 0


def _cmd_generate(args: argparse.Namespace) -> int:
    corpus = args.corpus.read_bytes()
    prompt = _read_prompt(args)
    backend = backends.get(args.backend)
    info = backends.info(args.backend)
    bw, la = SPEED_BUDGET[info.speed]
    cfg = GenerationConfig(
        length=args.length,
        beam_width=args.beam_width or bw,
        lookahead=args.lookahead or la,
        temperature=args.temperature,
        context_bytes=args.context_bytes or 0,
        memory=args.memory,
        tiebreak=args.tiebreak,
        corpus_gate=args.corpus_gate,
        repeat_penalty=args.repeat_penalty,
        workers=args.workers,
        seed=args.seed,
        backend_options=_parse_opt(args.opt),
    )
    res = generate(backend, corpus, prompt, cfg)
    sys.stdout.write((prompt + res.text).decode("utf-8", errors="replace"))
    sys.stdout.write("\n")
    if args.stats:
        print(
            f"[{res.backend}] {res.elapsed:.2f}s  {res.bytes_per_second:.1f}B/s  "
            f"{res.bits_per_byte:.2f}bits/B  copy={corpus_overlap(res.text, corpus):.0%}  "
            f"self-rep={self_repetition(res.text):.0%}  evals={res.evaluations}",
            file=sys.stderr,
        )
    return 0


def _cmd_compare(args: argparse.Namespace) -> int:
    corpus = args.corpus.read_bytes()
    prompt = _read_prompt(args)
    names = None if args.backends == "all" else [s.strip() for s in args.backends.split(",")]
    rows = run_comparison(
        corpus,
        prompt,
        length=args.length,
        names=names,
        temperature=args.temperature,
        workers=args.workers,
        seed=args.seed,
        beam_width=args.beam_width,
        lookahead=args.lookahead,
        context_bytes=args.context_bytes,
        memory=args.memory,
        tiebreak=args.tiebreak,
        corpus_gate=args.corpus_gate,
        repeat_penalty=args.repeat_penalty,
        backend_options=_parse_opt(args.opt),
    )
    md = render_markdown(rows, prompt=prompt.decode("utf-8", errors="replace"))
    if args.no_write:
        print(md)
    else:
        path = write_report(rows, args.out, prompt=prompt.decode("utf-8", errors="replace"))
        print(md.split("## outputs")[0].rstrip())
        print(f"\nreport written to {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if args.cmd == "backends":
        return _cmd_backends()
    if args.cmd == "generate":
        return _cmd_generate(args)
    if args.cmd == "compare":
        return _cmd_compare(args)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
