"""Generation engine: search continuations that compress best under a backend.

The loop is simple. Each round builds a scoring context from the tail of the
corpus plus a limited window of what has been generated so far, prepares a
:class:`~compression_lm.backends.base.Scorer` on it, then beam-searches
``lookahead`` bytes deep over the corpus alphabet and commits the winning
span. Hiding output older than ``memory`` bytes keeps the compressor from
matching against its own history, which would reward verbatim self-copying.

``beam_width=1`` + ``lookahead=1`` degenerates to per-byte greedy decoding;
raising ``temperature`` samples among the final beams instead of taking the
minimum, so the same machinery covers greedy, beam, and sampling strategies.
"""

from __future__ import annotations

import math
import random
import time
from collections.abc import Mapping, Sequence
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field

from .backends.base import Backend, Scorer


@dataclass(frozen=True)
class GenerationConfig:
    """Tuning knobs for one generation run."""

    #: Bytes of output to produce.
    length: int = 200
    #: Partial hypotheses kept at each depth of the beam search.
    beam_width: int = 16
    #: Span depth planned then committed per round.
    lookahead: int = 16
    #: 0 commits the most compressible span; >0 samples final beams with
    #: weight exp(-(score - best) / temperature), scores in bytes.
    temperature: float = 0.0
    #: Corpus tail bytes primed into the context (0 -> backend.context_limit).
    context_bytes: int = 0
    #: Generated bytes visible in the scoring context; older output is hidden
    #: so the compressor cannot score by copying its own history.
    memory: int = 128
    #: Extra bytes charged per reused n-gram inside a candidate span
    #: (0 disables). Discourages degenerate loops the memory window misses.
    repeat_penalty: float = 0.0
    #: N-gram size for repeat detection.
    repeat_ngram: int = 6
    #: How to order candidates tied on compressed length:
    #: "corpus" prefers candidates that still occur verbatim in the scoring
    #: context (a finer-grained signal than whole-byte lengths), "none" uses
    #: pure random tie-breaking. Compressed lengths are byte-granular, so
    #: ties are frequent and an unbiased tie-break matters.
    tiebreak: str = "corpus"
    #: With tiebreak="corpus", only score candidates that occur verbatim in
    #: the context (falls back to the full alphabet at dead ends). This is
    #: a 10-50x speedup — in-corpus continuations are rare, so nearly all
    #: compression calls are skipped — at the cost of ranking non-matching
    #: candidates only when no match exists. Output becomes strict
    #: recombination of corpus substrings.
    corpus_gate: bool = False
    #: Threads fanning out candidate scoring (measure() is thread-safe).
    workers: int = 1
    #: Wall-clock cap in seconds; None means "finish cfg.length". When set,
    # generation stops after the current span once the budget is spent and
    # the partial output is returned (result.elapsed ~<= budget).
    time_budget_sec: float | None = None
    #: Seed for temperature sampling; None for nondeterminism.
    seed: int | None = None
    #: Passed verbatim to Backend.prepare() (e.g. level, preset, quality).
    backend_options: Mapping[str, object] = field(default_factory=dict)


@dataclass
class GenerationResult:
    """Output plus the statistics needed for cross-backend comparison."""

    backend: str
    text: bytes
    elapsed: float
    evaluations: int
    total_cost: int
    config: GenerationConfig

    @property
    def bits_per_byte(self) -> float:
        """Mean conditional code length of the output — lower is "easier"."""
        return 8.0 * self.total_cost / max(1, len(self.text))

    @property
    def bytes_per_second(self) -> float:
        return len(self.text) / self.elapsed if self.elapsed else float("inf")


def corpus_alphabet(*parts: bytes) -> tuple[int, ...]:
    """Sorted byte values observed across ``parts``.

    A byte absent from the corpus can never extend a match, so it could only
    win on a tie; restricting the alphabet to observed bytes is a free
    speedup (roughly 256 -> ~80 for English text).
    """
    seen: set[int] = set()
    for part in parts:
        seen.update(part)
    return tuple(sorted(seen)) if seen else tuple(range(256))


def _ngrams(data: bytes, n: int) -> frozenset[bytes]:
    if n <= 0 or len(data) < n:
        return frozenset()
    return frozenset(data[i : i + n] for i in range(len(data) - n + 1))


def _repeat_hits(candidate: bytes, banned: frozenset[bytes], n: int) -> int:
    return sum(1 for i in range(len(candidate) - n + 1) if candidate[i : i + n] in banned)


def _measure(scorer: Scorer, cands: Sequence[bytes], pool: ThreadPoolExecutor | None) -> list[int]:
    if pool is not None:
        return list(pool.map(scorer.measure, cands))
    return scorer.measure_many(cands)


def _beam_span(
    scorer: Scorer,
    alphabet: tuple[int, ...],
    cfg: GenerationConfig,
    pool: ThreadPoolExecutor | None,
    banned: frozenset[bytes],
    rng: random.Random,
) -> tuple[list[bytes], list[int], int]:
    """Beam-search ``cfg.lookahead`` bytes deep.

    Returns the surviving beams, their *raw* conditional lengths (penalties
    excluded), and how many candidates were scored.
    """
    context = scorer.context
    beams = [b""]
    scores = [0]
    evaluations = 0
    gate = cfg.corpus_gate and cfg.tiebreak == "corpus"
    for _ in range(cfg.lookahead):
        cands = [h + bytes([b]) for h in beams for b in alphabet]
        if gate:
            members = [c for c in cands if c in context]
            if members:
                cands = members
        raw = _measure(scorer, cands, pool)
        evaluations += len(cands)
        if banned:
            adjusted = [
                r + cfg.repeat_penalty * _repeat_hits(c, banned, cfg.repeat_ngram)
                for c, r in zip(cands, raw, strict=True)
            ]
        else:
            adjusted = raw
        keys = [
            (
                adjusted[i],
                # Prefer continuations that remain verbatim corpus matches;
                # byte-granular lengths tie constantly, and an alphabetical
                # tie-break would bias toward low byte values (e.g. spaces).
                0 if cfg.tiebreak == "corpus" and cands[i] in context else 1,
                rng.random(),
            )
            for i in range(len(cands))
        ]
        keep = sorted(range(len(cands)), key=keys.__getitem__)[: cfg.beam_width]
        beams = [cands[i] for i in keep]
        scores = [raw[i] for i in keep]
    return beams, scores, evaluations


def _select(scores: Sequence[int], temperature: float, rng: random.Random) -> int:
    """Pick a final beam index. Beams arrive in ranking order."""
    if temperature <= 0 or len(scores) == 1:
        return 0
    best = min(scores)
    weights = [math.exp(-(s - best) / temperature) for s in scores]
    return rng.choices(range(len(scores)), weights=weights, k=1)[0]


def generate(
    backend: Backend,
    corpus: bytes,
    prompt: bytes,
    config: GenerationConfig | None = None,
) -> GenerationResult:
    """Generate ``config.length`` bytes continuing ``prompt``.

    ``backend`` may be any registered backend instance; ``corpus`` is the
    model's entire knowledge — output is necessarily a recombination of it.
    """
    cfg = config or GenerationConfig()
    rng = random.Random(cfg.seed)
    alphabet = corpus_alphabet(corpus, prompt)
    cap = min(cfg.context_bytes or backend.context_limit, backend.context_limit)
    corpus_tail = corpus[-cap:] if cap else b""

    out = bytearray()
    evaluations = 0
    total_cost = 0
    pool = ThreadPoolExecutor(cfg.workers) if cfg.workers > 1 else None
    started = time.perf_counter()
    try:
        while len(out) < cfg.length:
            if cfg.time_budget_sec is not None and (
                time.perf_counter() - started > cfg.time_budget_sec
            ):
                break
            recent = bytes(prompt) + bytes(out)
            context = corpus_tail + recent[-cfg.memory :] if cfg.memory else corpus_tail
            scorer = backend.prepare(context, **dict(cfg.backend_options))
            banned = (
                _ngrams(recent[-cfg.memory :], cfg.repeat_ngram)
                if cfg.repeat_penalty
                else frozenset()
            )
            beams, scores, ev = _beam_span(scorer, alphabet, cfg, pool, banned, rng)
            evaluations += ev
            idx = _select(scores, cfg.temperature, rng)
            total_cost += scores[idx]
            out += beams[idx]
    finally:
        if pool is not None:
            pool.shutdown(wait=False)

    return GenerationResult(
        backend=backend.name,
        text=bytes(out[: cfg.length]),
        elapsed=time.perf_counter() - started,
        evaluations=evaluations,
        total_cost=total_cost,
        config=cfg,
    )
